### ISSUE TITLE
Positioning fault

### ISSUE THREAD

**Issue by W1nd0x** [jeppesens/eufy-clean#11]
Hi! Thanks for making this integration. I have a strange Isseu. When running the room clean command from homeassitant the robot gives a positioning error. However doing so from the app and it runs fine. I tried it a few times to make sure it is not a random error. Does anyone else has this?

Using the command:
```
action: vacuum.send_command
target:
  entity_id: vacuum.robovac_x10_pro_omni
data:
  command: room_clean
  params:
    rooms:
      - 1
```
Which is my living room.
