### ISSUE TITLE
Room cleaning doesn't work

### ISSUE THREAD

**Issue by ne3x7** [jeppesens/eufy-clean#20]
I have a script like this
```
sequence:
  - action: vacuum.send_command
    metadata: {}
    data:
      command: room_clean
      params:
        rooms:
          - 6
    target:
      entity_id: vacuum.robovac_x10_pro_omni
```

It doesn't actually clean the room, robot begins positioning, immediately fails to determine its location and returns to dock. There's nothing particular in logs. What am I doing wrong?
