### ISSUE TITLE
Cannot find some Rooms

### ISSUE THREAD

**Issue by sjerocom** [jeppesens/eufy-clean#40]
Hey, first of all, thanks for your time to create this integration :)

this is one of my Scripts with working room:

```
alias: Wohnzimmer reinigen
sequence:
  - service: vacuum.send_command
    data:
      command: room_clean
      params:
        rooms: [9]
    target:
      entity_id: vacuum.goofy
```

when i put in a map_id i get an error: extra keys not allowed @ data['map_id']. Got None

so for room 1, 3, 4 and 9 it works - the base is in room 4 ....

well, i have 2 other rooms that i cannot find (i did go um to 30), and maybe i know why. both rooms has been detected as 2 smaller rooms, so i merged them (so it was 4 small rooms, now it is 2 correct ones) ... anyway, i cannot get the 2 merged rooms to work :(

any ideas on whats going on??

beside that, is it possible to send information, how the rooms should be cleaned (fanspeed is working, but with/without mop and how wet, cornercleaning?)
